# Use postgres/example user/password credentials
version: '3.9'

services:

  db:
    image: postgres:latest
    container_name: etl_db
    shm_size: 128mb
    ports:
      - 5432:5432
    volumes:
      - ./dump:/opt/dump
    env_file:
      - .db.env
    
    networks:
      - etl_logstash

  adminer:
    image: adminer
    restart: always
    ports:
      - 8888:8080
    networks:
      - etl_logstash

networks:
  etl_logstash: